Proxy Agent: Introduce custom result and error types
Azure/GuestProxyAgent pull request #134
Opened 2024-10-15 21:14 UTC by mayankdaruka-msft

This PR is addressing the feedback from #117.
```
I see std::io::Result being used as a custom result type (a common rookie error seen for example [here](https://github.com/Azure/GuestProxyAgent/blob/e4de0187c817080099503e28a76134345d961b15/proxy_agent/src/common/hyper_client.rs#L256-L257)), but really crates should define their own error and result types, leading to a nice 'branded' feeling API (e.g. in crate foo, foo::bar() might return a foo::Result which can hold a foo::Error). This is surprisingly straightforward to remedy, the usual way this is done is by using thiserror deriving a custom error type and making a new Result alias as follows (I like to put these next to one another in lib.rs
#[derive(Debug, thiserror::Error)]
pub enum Error {
    #[error("cannot foo")]
    Foo,
}

pub type Result<T> = std::result::Result<T, Error>
Doing this also has the added benefit of encouraging better error handling
```

Throughout the codebase, we see the usage of `Result` and `Error` types from the `std::io` library. Most of those errors are not I/O related and needed some re-defining. In this PR, we introduce our own type to be used in the proxy_agent crate.

The changes here do not move over all occurrences of std::io::Result usage in proxy agent code. There will be a subsequent PR that builds on top of the work here so we can keep the PRs smaller.

E2E Tests Link: https://msazure.visualstudio.com/One/_build/results?buildId=105933413&view=results

2024-10-15 23:49 UTC, ZhidongPeng requested changes

2024-10-15 23:49 UTC, ZhidongPeng commented on proxy_agent/src/common/error.rs
> +
nit: remove extra line break. it would be nice keep all the use statements together.

2024-10-15 23:49 UTC, ZhidongPeng commented on proxy_agent/Cargo.toml
> +thiserror = "1.0.64"
Cargo.lock file missed?

2024-10-16 03:23 UTC, LittleBoxOfSunshine commented on proxy_agent/Cargo.toml
> +thiserror = "1.0.64"
That reminds me, if we add [--locked](https://doc.rust-lang.org/cargo/commands/cargo-build.html#manifest-options) to the cargo build step in the pipeline that will catch this error and increases security + determinism.

2024-10-16 14:58 UTC, mayankdaruka-msft commented on proxy_agent/src/common/error.rs
> +
Done, thanks.

2024-10-16 18:55 UTC, ZhidongPeng approved these changes

2024-10-16 23:06 UTC, merged