Move over remaining errors to custom types
Azure/GuestProxyAgent pull request #149
Opened 2024-11-04 16:17 UTC by mayankdaruka-msft

This PR moves over remaining errors to our custom types defined within each crate. Changes here are in multiple crates (extension, agent, and setup). Builds on top of my previous PRs.

2024-11-04 17:47 UTC, shahneerali commented on proxy_agent_extension/src/handler_main.rs
> -                process::exit(constants::EXIT_CODE_NO_CONFIG_SEQ_NO);
contants.rs also needs to be updated to remove unused exit codes

2024-11-04 17:50 UTC, shahneerali commented on proxy_agent_extension/src/common.rs
> +                "no seq no found, writing seq no {} to file",
please keep log messages similar to current, include enable command here

2024-11-04 17:52 UTC, ZhidongPeng requested changes, later dismissed

2024-11-04 17:52 UTC, ZhidongPeng commented on proxy_agent_extension/src/common.rs
> +    config_seq_no: &String,
&str?

![image](https://github.com/user-attachments/assets/a16acd73-fa4d-459a-9bae-e0501d9e4aac)

2024-11-04 17:52 UTC, ZhidongPeng commented on proxy_agent_extension/src/common.rs
> +    config_seq_no: &String,
`&str`, same here

2024-11-04 17:52 UTC, ZhidongPeng commented on proxy_agent_extension/src/common.rs
> +    config_seq_no: &String,
and other places.

2024-11-04 17:52 UTC, ZhidongPeng commented on proxy_agent_extension/src/main.rs
> +#[derive(Debug, thiserror::Error)]
please move to a new rs file as proxy_agent and proxy_agent_shared crate

2024-11-12 18:16 UTC, mayankdaruka-msft commented on proxy_agent_extension/src/common.rs
> +    config_seq_no: &String,
Changed, thanks.

2024-11-12 18:19 UTC, mayankdaruka-msft commented on proxy_agent_extension/src/common.rs
> +                "no seq no found, writing seq no {} to file",
Log messages are the same here, "No config seq no found for enable command" was never being logged in the first place.

2024-11-13 19:34 UTC, shahneerali commented on Cargo.lock
revert file

2024-11-13 21:18 UTC, shahneerali commented on proxy_agent_extension/src/main.rs
> +        handler_main::program_start(command, config_seq_no);
removing the Option field for config_seq_no may not have any consequences, but how does it help besides removing some errors which could instead be replaced with custom errors?

2024-11-14 16:35 UTC, mayankdaruka-msft commented on proxy_agent_extension/src/main.rs
> +        handler_main::program_start(command, config_seq_no);
Since there wasn't any usage of the 'None' option, I removed it since it helps simplify the codebase by reducing ambiguity with regards to the value of config_seq_no and minimizing the number of cases we need to account for.

2024-11-14 16:38 UTC, mayankdaruka-msft commented on Cargo.lock
Dependency change in Cargo.toml requires an update to Cargo.lock.

2024-11-19 19:38 UTC, shahneerali approved these changes

2024-11-19 20:22 UTC, ZhidongPeng commented on proxy_agent_extension/src/constants.rs
> +pub const EXIT_CODE_NOT_SUPPORTED_OS_VERSION: i32 = 6;
@shahneerali , we need update our TSG about the error code agin.

2024-11-19 21:04 UTC, shahneerali commented on proxy_agent_extension/src/constants.rs
> +pub const EXIT_CODE_NOT_SUPPORTED_OS_VERSION: i32 = 6;
TSG is updated to reflect this

2024-11-20 03:08 UTC, merged